input {
  file {
    path => "/reports/*.json"
    start_position => "beginning"
    sincedb_path => "/tmp/devsecops-reports.sincedb"
    mode => "read"
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "project" => "sna-devsecops"
      "source_type" => "security-scan-report"
    }
  }

  if [Issues] {
    mutate {
      add_field => { "scanner" => "gosec" }
    }
  } else if [Results] {
    mutate {
      add_field => { "scanner" => "trivy" }
    }
  } else {
    mutate {
      add_field => { "scanner" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "devsecops-security-reports"
  }

  stdout {
    codec => rubydebug
  }
}
